version: 0.2
phases:
  build:
    commands:
      - echo Entered build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build Completed Succesfully
artifact
  files:
    -  target/test.jar
  discard-paths: yes
    
